id: P9BDF5192
initial_creation_type: input
source_metadata:
  title: Jamgön Kongtrul Lodrö Thaye Series
  language: de
  description: Works by or about the great nineteenth century master Jamgön Kongtrul
    Lodrö Thaye ('jam mgon kong sprul blo gros mtha' yas, 1813–1899), one of the pioneers
    of the Rimé movement
  volume:
    400fd5fdde484d82b7e5c6ce62fdfac8:
      title: Advice to Lhawang Tashi
      parent: Advice
    4a477fe1fdcd4232b6dc2bac399a4ac1:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    fae5a0d48cdf47aaaf38de92f4f14d2d:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    b0c03edf5f494894b1d578c55bff76b1:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    7b11d092317c4e75aa42a5020a3705c3:
      title: Prayer for Peace and Stability in Tibet
      parent: Aspiration Prayers
    d43e1422301a4090adf452b53e739b6c:
      title: The Indestructible Vajra Garland, An Aspiration Prayer for the Lives
        of the Supreme Holders of the Non-Sectarian Teachings
      parent: Aspiration Prayers
    c4608673d7fb44eaaa5de43b39035adf:
      title: 'A Garland of Vajra Gems: The Life and Liberation of the Guru'
      parent: Biography
    64a646ee951240f9b1b23f637cbf4132:
      title: Biography of Jamgön Kongtrul Lodrö Thaye
      parent: Biography
    41c787650b72444698680c4b35781a46:
      title: The Life and Liberation of Padmākara, the Second Buddha from A Precious
        Garland of Lapis Lazuli
      parent: Biography
    b5f8f005abfa41fc87efceebab1a35bd:
      title: 'Calling the Guru From Afar: A Prayer to Pierce the Heart with Devotion'
      parent: Calling the Guru From Afar
    4daf3d2f6d9b47b7b84169c8bc187762:
      title: Ārya Mañjuśrī Tantra Garbha—commentary
      parent: Commentaries
    c6e22656da144a6a95b1b8f34637fc79:
      title: 'The Cascading Essence of Great Bliss: An Empowerment Ritual for the
        Female Practice of the Queen of Great Bliss, from the Heart Essence of the
        Vast Expanse'
      parent: Empowerment Rites
    04d61a0759cd4f25a3b95ebface5ca09:
      title: 'Jewels of Many Colours: Ordinary Fire Pūjas for the Four Activities
        Based on a Single Substance to Easily Conclude Approach and Accomplishment'
      parent: Fire Offering
    d11c2c7b796540dfacf21a8879d2a05b:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Guru Rinpoche Prayers
    803cf2ac54ae4a5ca1534f43281c8774:
      title: 'The Fount of Longevity: The Chimé Pakmé Nyingtik Lineage Prayer'
      parent: Lineage Prayers
    a3d0562cc237426d97202178af59450d:
      title: A Short Supplication to Tārā
      parent: Prayers
    a8d354caa9d1441799bbc4824e371724:
      title: Prayer to Jamyang Khyentse Wangpo, Jamgön Kongtrul and Jamyang Khyentse
        Chökyi Lodrö
      parent: Prayers
    aa1aa29c76624864958acbfd9482a599:
      title: Prayer to Khyentse Wangpo, Kongtrul and Chokgyur Lingpa
      parent: Prayers
    d80f5e33708548c1a5b2d1c3a3eb2683:
      title: 'The Melodious Sound of Gathering Auspiciousness: A Prayer Based on the
        Liberational Life of the Omniscient Jamyang Khyentse Wangpo'
      parent: Prayers
    267c3d8d3d834667a67a5b447bd7cfd0:
      title: 'The Melodious Speech of Samantabhadra: A Prayer to the Glorious Master
        Jamgön Kongtrul Thaye'
      parent: Prayers
    6a6f100254ee49e0b7de9f9d345f0c44:
      title: 'The Tambura’s Yearning Song of Devotion: A Prayer Summarizing Khandro
        Yeshe Tsogyal’s Life and Liberation'
      parent: Prayers
    f04b1203c91d492ca4f897f4c0be8546:
      title: 'The Essence of Benefit and Happiness: A Method for Saving Lives'
      parent: Saving Lives
    34429d19b47c4e7c91560a1d4f7c3765:
      title: Prayer to Kongtrul Yönten Gyatso
      parent: Swift Rebirth Prayers
    3a107a9abf604433ac39733a02842e38:
      title: 'Music to Adorn the Illusory Display: A Concise Explanation of the Nature
        of the Feast Offering'
      parent: Tsok
    ecb32d546e6a4ab8b4b0180238b708b0:
      title: Vajrakīla Tsok Prayer from Sangtik Korsum
      parent: Tsok
created_at: '2022-02-28T23:32:21.217318'
last_modified_at: '2022-02-28T23:32:21.217321'
